package com.mingsu.model;

import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.log4j.Logger;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	private static Logger logger = Logger.getLogger(_MappingKit.class);
	private static final SimpleDateFormat monthdatefmt = new SimpleDateFormat("yyyyMM");
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("user", "userid", User.class);
//		arp.addMapping(getMonthTableName("tbl_latteread_log_"), "id", MyLog.class);
	}
	
	
	/**
	 * 获取月表名
	 */
	private static String getMonthTableName(String tableNamePrefix) {

		try{
			return tableNamePrefix + monthdatefmt.format(new Date());
		}
		catch (Exception e) {
			logger.error("+++get TableName = " + tableNamePrefix + " error, exception : ", e);
			return null;
		}
	}
}

