package com.mingsu.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
//@SuppressWarnings({"serial","unchecked"})
@SuppressWarnings({"serial"})
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {
	
}
